# The potential behaviors to be given to GPT. A specified amount will be chosen to either be liked, or disliked.
potentialBehaviors: ["killing animals",
                     "fighting other players",
                     "slaying monsters",
                     "using hostile language",
                     "using vulgar language",
                     "using friendly language",
                     "building structures of worship",
                     "building non-religious structures",
                     "materialistic wants",
                     "helping other players",
                     "connecting with animals",
                     "growing plants",
                     "using fire and explosions",
                     "love between players",
                     "sexual behaviour",
                     "generosity",
                     "ritual sacrifice",
                     "eating meat"]
apiKey: "YOUR_API_KEY"